In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [4]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2013-01-01 -2.231136  0.743791  0.234638 -0.938229
2013-01-02 -0.471853  0.032592 -0.501174  1.187208
2013-01-03 -1.146970 -0.033943  0.020818 -0.017207
2013-01-04  1.488961 -0.774059  0.600891  0.914173
2013-01-05 -0.013974 -0.173201  0.501213 -0.703841
2013-01-06  0.866301 -1.047280  0.944520 -0.442230

In [5]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1,index=list(range(4)),dtype="float32"),
        "D": np.array([3]*4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo", #특이한게 ,로 끝내도 되고 아닌 것으로 끝내도 되네?
    }
)
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [6]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [7]:
#df2.<TAB> # noqa: E225, E999

#df2.까지 입력후 탭누르라는 의미, vscode에서는 탭안눌러도 자동으로 표시 단 컬럼은 안 표시됨

In [8]:
df.head()

A         B         C         D
2013-01-01 -2.231136  0.743791  0.234638 -0.938229
2013-01-02 -0.471853  0.032592 -0.501174  1.187208
2013-01-03 -1.146970 -0.033943  0.020818 -0.017207
2013-01-04  1.488961 -0.774059  0.600891  0.914173
2013-01-05 -0.013974 -0.173201  0.501213 -0.703841

In [9]:
df.tail(3)

A         B         C         D
2013-01-04  1.488961 -0.774059  0.600891  0.914173
2013-01-05 -0.013974 -0.173201  0.501213 -0.703841
2013-01-06  0.866301 -1.047280  0.944520 -0.442230

In [10]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [11]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [12]:
df.to_numpy()

array([[-2.2311363 ,  0.74379092,  0.23463822, -0.93822926],
       [-0.47185276,  0.03259189, -0.50117394,  1.18720791],
       [-1.14697035, -0.0339433 ,  0.02081781, -0.01720698],
       [ 1.4889611 , -0.77405854,  0.60089103,  0.91417312],
       [-0.01397351, -0.17320098,  0.50121337, -0.70384064],
       [ 0.86630071, -1.04727953,  0.94452009, -0.44222962]])

In [13]:
df.values

array([[-2.2311363 ,  0.74379092,  0.23463822, -0.93822926],
       [-0.47185276,  0.03259189, -0.50117394,  1.18720791],
       [-1.14697035, -0.0339433 ,  0.02081781, -0.01720698],
       [ 1.4889611 , -0.77405854,  0.60089103,  0.91417312],
       [-0.01397351, -0.17320098,  0.50121337, -0.70384064],
       [ 0.86630071, -1.04727953,  0.94452009, -0.44222962]])

In [14]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [15]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [16]:
df2.values

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [17]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.251445 -0.208683  0.300151 -0.000021
std    1.349406  0.635627  0.504088  0.873694
min   -2.231136 -1.047280 -0.501174 -0.938229
25%   -0.978191 -0.623844  0.074273 -0.638438
50%   -0.242913 -0.103572  0.367926 -0.229718
75%    0.646232  0.015958  0.575972  0.681328
max    1.488961  0.743791  0.944520  1.187208

In [18]:
df.T
#행과 열을 바꿔주는데 미리 계산되어 있음
#메소드가 아닌 속성임

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -2.231136   -0.471853   -1.146970    1.488961   -0.013974    0.866301
B    0.743791    0.032592   -0.033943   -0.774059   -0.173201   -1.047280
C    0.234638   -0.501174    0.020818    0.600891    0.501213    0.944520
D   -0.938229    1.187208   -0.017207    0.914173   -0.703841   -0.442230

In [19]:
df.T.index
#값만 바꿔서 나타내는가해서 확인용으로 해줬는데 인덱스도 확실히 바뀌어있다

Index(['A', 'B', 'C', 'D'], dtype='object')

In [20]:
df.sort_index(axis=1, ascending=False)
#axis = 1 하면 열끼리 정렬하는 것

D         C         B         A
2013-01-01 -0.938229  0.234638  0.743791 -2.231136
2013-01-02  1.187208 -0.501174  0.032592 -0.471853
2013-01-03 -0.017207  0.020818 -0.033943 -1.146970
2013-01-04  0.914173  0.600891 -0.774059  1.488961
2013-01-05 -0.703841  0.501213 -0.173201 -0.013974
2013-01-06 -0.442230  0.944520 -1.047280  0.866301

In [21]:
df.sort_values(by="B")
#df안에 있는 특정 열의 값에 대해서 정렬해줄 수 있음

A         B         C         D
2013-01-06  0.866301 -1.047280  0.944520 -0.442230
2013-01-04  1.488961 -0.774059  0.600891  0.914173
2013-01-05 -0.013974 -0.173201  0.501213 -0.703841
2013-01-03 -1.146970 -0.033943  0.020818 -0.017207
2013-01-02 -0.471853  0.032592 -0.501174  1.187208
2013-01-01 -2.231136  0.743791  0.234638 -0.938229

In [22]:
df["A"]

2013-01-01   -2.231136
2013-01-02   -0.471853
2013-01-03   -1.146970
2013-01-04    1.488961
2013-01-05   -0.013974
2013-01-06    0.866301
Freq: D, Name: A, dtype: float64

In [23]:
df[0:3]

A         B         C         D
2013-01-01 -2.231136  0.743791  0.234638 -0.938229
2013-01-02 -0.471853  0.032592 -0.501174  1.187208
2013-01-03 -1.146970 -0.033943  0.020818 -0.017207

In [24]:
df["20130102":"20130104"]

A         B         C         D
2013-01-02 -0.471853  0.032592 -0.501174  1.187208
2013-01-03 -1.146970 -0.033943  0.020818 -0.017207
2013-01-04  1.488961 -0.774059  0.600891  0.914173

In [25]:
df.loc[dates[0]]

A   -2.231136
B    0.743791
C    0.234638
D   -0.938229
Name: 2013-01-01 00:00:00, dtype: float64

In [27]:
df.loc[dates[0],:]

A   -2.231136
B    0.743791
C    0.234638
D   -0.938229
Name: 2013-01-01 00:00:00, dtype: float64

In [26]:
df.loc[:,["A","B"]]

A         B
2013-01-01 -2.231136  0.743791
2013-01-02 -0.471853  0.032592
2013-01-03 -1.146970 -0.033943
2013-01-04  1.488961 -0.774059
2013-01-05 -0.013974 -0.173201
2013-01-06  0.866301 -1.047280

In [28]:
df.loc["20130102":"20130104",["A","B"]]

A         B
2013-01-02 -0.471853  0.032592
2013-01-03 -1.146970 -0.033943
2013-01-04  1.488961 -0.774059

In [29]:
df.loc["20130102":"20130104",["B","A"]]

B         A
2013-01-02  0.032592 -0.471853
2013-01-03 -0.033943 -1.146970
2013-01-04 -0.774059  1.488961

In [30]:
df.loc[dates[0],"A"]

-2.231136296456531

In [31]:
df.at[dates[0],"A"]

-2.231136296456531

In [32]:
df.iloc[3]

A    1.488961
B   -0.774059
C    0.600891
D    0.914173
Name: 2013-01-04 00:00:00, dtype: float64

In [33]:
df.iloc[3:5, 0:2]

A         B
2013-01-04  1.488961 -0.774059
2013-01-05 -0.013974 -0.173201

In [38]:
#비교 loc는 슬라이싱 할때 끝부분까지로 인식(끝부분 포함됨) iloc는 끝부분제외
#df.loc[3:5, 0:2] 아 맞다 이런 식으로 숫자 인덱스로 안됬다
df.loc["20130104":"20130105", "A":"B"]

A         B
2013-01-04  1.488961 -0.774059
2013-01-05 -0.013974 -0.173201

In [39]:
df.iloc[[1,2,4],[0,2]]

A         C
2013-01-02 -0.471853 -0.501174
2013-01-03 -1.146970  0.020818
2013-01-05 -0.013974  0.501213

In [40]:
df.iloc[1:3, :]

A         B         C         D
2013-01-02 -0.471853  0.032592 -0.501174  1.187208
2013-01-03 -1.146970 -0.033943  0.020818 -0.017207

In [41]:
df.iloc[:, 1:3]

B         C
2013-01-01  0.743791  0.234638
2013-01-02  0.032592 -0.501174
2013-01-03 -0.033943  0.020818
2013-01-04 -0.774059  0.600891
2013-01-05 -0.173201  0.501213
2013-01-06 -1.047280  0.944520

In [42]:
df.iloc[1,1]

0.032591890081159224

In [43]:
df.iat[1,1]

0.032591890081159224

In [44]:
df[df["A"] > 0]

A         B         C         D
2013-01-04  1.488961 -0.774059  0.600891  0.914173
2013-01-06  0.866301 -1.047280  0.944520 -0.442230

In [45]:
df[df>0]

A         B         C         D
2013-01-01       NaN  0.743791  0.234638       NaN
2013-01-02       NaN  0.032592       NaN  1.187208
2013-01-03       NaN       NaN  0.020818       NaN
2013-01-04  1.488961       NaN  0.600891  0.914173
2013-01-05       NaN       NaN  0.501213       NaN
2013-01-06  0.866301       NaN  0.944520       NaN

In [47]:
df2=df.copy()
df2["E"]=["one", "one", "two", "three", "four", "three"]
df2

A         B         C         D      E
2013-01-01 -2.231136  0.743791  0.234638 -0.938229    one
2013-01-02 -0.471853  0.032592 -0.501174  1.187208    one
2013-01-03 -1.146970 -0.033943  0.020818 -0.017207    two
2013-01-04  1.488961 -0.774059  0.600891  0.914173  three
2013-01-05 -0.013974 -0.173201  0.501213 -0.703841   four
2013-01-06  0.866301 -1.047280  0.944520 -0.442230  three

In [52]:
df2[df2["E"].isin(["two", "four"])]
#isin()안에 []로 넣어야하는 듯 (한 개의 경우에도)

A         B         C         D     E
2013-01-03 -1.146970 -0.033943  0.020818 -0.017207   two
2013-01-05 -0.013974 -0.173201  0.501213 -0.703841  four

In [53]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range("20130102", periods=6))
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [54]:
df["F"]=s1

In [58]:
df.at[dates[0],"A"] = 0
df

A         B         C         D    F
2013-01-01  0.000000  0.743791  0.234638 -0.938229  NaN
2013-01-02 -0.471853  0.032592 -0.501174  1.187208  1.0
2013-01-03 -1.146970 -0.033943  0.020818 -0.017207  2.0
2013-01-04  1.488961 -0.774059  0.600891  0.914173  3.0
2013-01-05 -0.013974 -0.173201  0.501213 -0.703841  4.0
2013-01-06  0.866301 -1.047280  0.944520 -0.442230  5.0

In [60]:
df.iat[0, 1] = 0
df

A         B         C         D    F
2013-01-01  0.000000  0.000000  0.234638 -0.938229  NaN
2013-01-02 -0.471853  0.032592 -0.501174  1.187208  1.0
2013-01-03 -1.146970 -0.033943  0.020818 -0.017207  2.0
2013-01-04  1.488961 -0.774059  0.600891  0.914173  3.0
2013-01-05 -0.013974 -0.173201  0.501213 -0.703841  4.0
2013-01-06  0.866301 -1.047280  0.944520 -0.442230  5.0

In [63]:
len(df)

6

In [62]:
df.loc[:, "D"] = np.array([5]*len(df))
df

A         B         C    D    F
2013-01-01  0.000000  0.000000  0.234638  5.0  NaN
2013-01-02 -0.471853  0.032592 -0.501174  5.0  1.0
2013-01-03 -1.146970 -0.033943  0.020818  5.0  2.0
2013-01-04  1.488961 -0.774059  0.600891  5.0  3.0
2013-01-05 -0.013974 -0.173201  0.501213  5.0  4.0
2013-01-06  0.866301 -1.047280  0.944520  5.0  5.0

In [66]:
df2 = df.copy()
df2[df2 > 0] = -df2
df2

A         B         C    D    F
2013-01-01  0.000000  0.000000 -0.234638 -5.0  NaN
2013-01-02 -0.471853 -0.032592 -0.501174 -5.0 -1.0
2013-01-03 -1.146970 -0.033943 -0.020818 -5.0 -2.0
2013-01-04 -1.488961 -0.774059 -0.600891 -5.0 -3.0
2013-01-05 -0.013974 -0.173201 -0.501213 -5.0 -4.0
2013-01-06 -0.866301 -1.047280 -0.944520 -5.0 -5.0

자동으로 commit되게 yml추가해준 것 테스트용도