In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [4]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2013-01-01  0.339251  0.205104  0.245565  0.989844
2013-01-02 -0.247636 -0.310176  0.313418  1.311206
2013-01-03  0.171147 -0.091449 -0.642168  0.787092
2013-01-04 -1.023564 -1.009003 -0.192593  0.067722
2013-01-05 -0.963123  0.439623 -1.338136 -0.318223
2013-01-06  0.700625  0.667615  0.838370 -1.292050

In [5]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1,index=list(range(4)),dtype="float32"),
        "D": np.array([3]*4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo", #특이한게 ,로 끝내도 되고 아닌 것으로 끝내도 되네?
    }
)
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [6]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [7]:
#df2.<TAB> # noqa: E225, E999

#df2.까지 입력후 탭누르라는 의미, vscode에서는 탭안눌러도 자동으로 표시 단 컬럼은 안 표시됨

In [8]:
df.head()

A         B         C         D
2013-01-01  0.339251  0.205104  0.245565  0.989844
2013-01-02 -0.247636 -0.310176  0.313418  1.311206
2013-01-03  0.171147 -0.091449 -0.642168  0.787092
2013-01-04 -1.023564 -1.009003 -0.192593  0.067722
2013-01-05 -0.963123  0.439623 -1.338136 -0.318223

In [9]:
df.tail(3)

A         B         C         D
2013-01-04 -1.023564 -1.009003 -0.192593  0.067722
2013-01-05 -0.963123  0.439623 -1.338136 -0.318223
2013-01-06  0.700625  0.667615  0.838370 -1.292050

In [10]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [11]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [12]:
df.to_numpy()

array([[ 0.33925128,  0.20510389,  0.24556543,  0.98984381],
       [-0.24763586, -0.3101758 ,  0.31341775,  1.31120552],
       [ 0.17114682, -0.09144923, -0.6421679 ,  0.78709159],
       [-1.02356432, -1.00900303, -0.19259343,  0.06772172],
       [-0.96312322,  0.43962253, -1.33813628, -0.31822304],
       [ 0.70062514,  0.66761484,  0.8383699 , -1.2920502 ]])

In [13]:
df.values

array([[ 0.33925128,  0.20510389,  0.24556543,  0.98984381],
       [-0.24763586, -0.3101758 ,  0.31341775,  1.31120552],
       [ 0.17114682, -0.09144923, -0.6421679 ,  0.78709159],
       [-1.02356432, -1.00900303, -0.19259343,  0.06772172],
       [-0.96312322,  0.43962253, -1.33813628, -0.31822304],
       [ 0.70062514,  0.66761484,  0.8383699 , -1.2920502 ]])

In [14]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [15]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [16]:
df2.values

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [17]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.170550 -0.016381 -0.129257  0.257598
std    0.706732  0.600349  0.774756  0.969089
min   -1.023564 -1.009003 -1.338136 -1.292050
25%   -0.784251 -0.255494 -0.529774 -0.221737
50%   -0.038245  0.056827  0.026486  0.427407
75%    0.297225  0.380993  0.296455  0.939156
max    0.700625  0.667615  0.838370  1.311206

In [21]:
df.T
#행과 열을 바꿔주는데 미리 계산되어 있음
#메소드가 아닌 속성임

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.339251   -0.247636    0.171147   -1.023564   -0.963123    0.700625
B    0.205104   -0.310176   -0.091449   -1.009003    0.439623    0.667615
C    0.245565    0.313418   -0.642168   -0.192593   -1.338136    0.838370
D    0.989844    1.311206    0.787092    0.067722   -0.318223   -1.292050

In [23]:
df.T.index
#값만 바꿔서 나타내는가해서 확인용으로 해줬는데 인덱스도 확실히 바뀌어있다

Index(['A', 'B', 'C', 'D'], dtype='object')

In [24]:
df.sort_index(axis=1, ascending=False)
#axis = 1 하면 열끼리 정렬하는 것

D         C         B         A
2013-01-01  0.989844  0.245565  0.205104  0.339251
2013-01-02  1.311206  0.313418 -0.310176 -0.247636
2013-01-03  0.787092 -0.642168 -0.091449  0.171147
2013-01-04  0.067722 -0.192593 -1.009003 -1.023564
2013-01-05 -0.318223 -1.338136  0.439623 -0.963123
2013-01-06 -1.292050  0.838370  0.667615  0.700625

In [25]:
df.sort_values(by="B")
#df안에 있는 특정 열의 값에 대해서 정렬해줄 수 있음

A         B         C         D
2013-01-04 -1.023564 -1.009003 -0.192593  0.067722
2013-01-02 -0.247636 -0.310176  0.313418  1.311206
2013-01-03  0.171147 -0.091449 -0.642168  0.787092
2013-01-01  0.339251  0.205104  0.245565  0.989844
2013-01-05 -0.963123  0.439623 -1.338136 -0.318223
2013-01-06  0.700625  0.667615  0.838370 -1.292050